name: "Terraform Destroy All"

on:
  workflow_dispatch:

jobs:
  terraform-destroy:
    name: "Destroy Infra and RDS"
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout Code"
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: "Configure AWS Credentials"
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Update kubeconfig
        run: aws eks update-kubeconfig --name techchallenge --region us-east-1

      - name: "Destroy Kubernetes Resources"
        run: |
          echo "Step 1: Destroying Kubernetes Resources"
          kubectl delete deployments --all -n default
          kubectl delete replicasets --all -n default
          kubectl delete statefulsets --all -n default
          kubectl delete services --all -n default
          kubectl delete pods --all -n default
          kubectl delete pvc --all -n default
          kubectl delete hpa --all -n default
          kubectl delete pv --all
          kubectl delete role --all
          kubectl delete rolebinding --all
          kubectl delete configmap --all
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}

      - name: "Setup Terraform"
        uses: hashicorp/setup-terraform@v1

      - name: "Terraform Init - RDS"
        run: |
          echo "Step 4: Initializing Terraform for RDS"
          terraform init -backend-config="bucket=${{ secrets.AWS_BUCKET_NAME }}" \
          -backend-config="key=rds/estado/terraform.tfstate" \
          -backend-config="region=us-east-1"
        working-directory: rds/
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}

      - name: "Terraform Destroy - RDS"
        run: |
          echo "Step 5: Destroying RDS"
          terraform destroy -auto-approve
        working-directory: rds/
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}

      - name: "Terraform Init - Infrastructure"
        run: |
          echo "Step 2: Initializing Terraform for Infra"
          terraform init -backend-config="bucket=${{ secrets.AWS_BUCKET_NAME }}" \
          -backend-config="key=infra/estado/terraform.tfstate" \
          -backend-config="region=us-east-1"
        working-directory: infra/
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}

      - name: "Terraform Destroy - Infrastructure"
        run: |
          echo "Step 3: Destroying Infrastructure"
          terraform destroy -auto-approve
        working-directory: infra/
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}