name: "Terraform Infra"

on:
  push: 
    branches: ["main"]
    paths: ["terraform/**"]
  workflow_dispatch:

jobs:
  terraform:
    name: "Terraform Apply"
    runs-on: "ubunto-latest"
    steps:
      - name: "Configure AWS Credentials"
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          ws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
